


<form method="POST" action="mostrarcategorias">
        <label for="genero">Selecciona un genero musical:</label>
        <select id="genero" name="genero">
<?php foreach($categorias as $album): ?>
            
                    
           
            <option ><a href="categorias/<?php echo $album->id_album?>" ><?=$album->genero?></a></option>
            <?php
                  endforeach;?>
        </select>
        <input type="submit" value="Enviar">
    </form>

    
