<?php

?>
<form action="agregar" method="POST" >
<div class="formu">

<label >nombre</label>
<input type="text" name="nombre">

<label for="">canciones</label>
<input type="text" name="canciones">

<label for="">duracion</label>
<input type="text" name="duracion">

<label for="">artista</label>
<input type="text" name="artista">

<label for="">genero</label>
<input type="text" name="genero">

<label for="">lanzamiento</label>
<input type="date" name="lanzamiento">

<label for="">Precio</label>
<input type="text" name = "precio">

<button type="submit" >enviar</button>
</div>


</form>


<div class="m-auto" style="width: 80rem; ">
              <ul  class="list-group">
            
                
            <?php foreach($items as $album): ?>
            
                    
                    <li class="list-group-item navbar-expand-lg ">
                    <a  href="ver"><?=$album->nombre?> </a>
                  <a href="borrar/<?php echo $album->id_album?>">borrar</a>  
                  <a href="editar/ <?php echo $album->id_album?>">editar</a>

                    
            
                  </li>
                    
                
                
                  
                          <?php
                          endforeach;?>
                </ul>  