<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>



<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="home">Musica</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        
        <!-- <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="administrar">Administracion</a>
        </li> -->
  
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="listarVentas">Ventas</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="login">Iniciar Session</a>
        </li>
        
        <!-- <li class="nav-item">
          <a class="nav-link" href="home">Albumes</a> -->
        
        <!-- </li> <li class="nav-item">
          <a class="nav-link" href="categorias">Albumes por Categorias</a>
        </li> -->
       
        </li> <li class="nav-item">
          <a class="nav-link" href="logout"> Log Out</a>
        </li>

      </ul>
    </div>
  </div>
</nav>
  
</body>
</html>