<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="m-auto" style="width: 50rem; ">
           <ul class="list-group">
           <li class="list-group-item">
       Nombre album
        </li>
            
                
<?php foreach($items as $album): ?>

		
        <li class="list-group-item navbar-expand-lg ">
        <a href="ver/<?php echo $album->id_album?>" ><?=$album->nombre?></a>
        </li>
        
    
    
      
              <?php
              endforeach;?>
    </ul>         
               
    <ul class="list-group">
            
                
                  
                         
            
            </div>
              </body>
</html>