<div class="m-auto" style="width: 80rem; ">
              <ul  class="list-group">
            
                
            <?php foreach($item as $ventas): ?>
            
                    
                    <li class="list-group-item navbar-expand-lg ">
                    <a  href="verVenta/<?=$ventas->id?>" <?=$ventas->id?>> <?=$ventas->id?> </a>
                    
                    <?= $ventas->nombre_album?>
                    <?= $ventas->tipo?>
                    <?= $ventas->via?>
                    <?= $ventas->precio?>

                    <a href="borrarVenta/<?= $ventas->id?>"> Borrar </a>
                    <a href="mostrarEditVenta/<?= $ventas->id?>"> Editar </a>
        
                  </li>
                    
                
                
                  
                          <?php
                          endforeach;?>
                </ul> 