<ul>
            
                
            <?php foreach($items as $albumes): ?>
                    
                    <li>
                    <?=$albumes->nombre, $albumes->canciones,$albumes->artista?>
            </li>
           
                
                  
                          <?php
                          endforeach;?>
                </ul>         
                           