
<table class="table m-auto" style="width: 75rem; ">
<thead class="table-dark">
        <th>nombre album</th>
        <th>cantidad de canciones</th>
        <th>duracion </th>
        <th>artistas </th>
        <th>genero</th>
        <th>lanzamiento </th>
        </tr>
        </thead>

 

		<tr>
                        <?php var_dump($id); ?>
			<td> <?=$id->nombre?> </td>
			<td> <?=$id->canciones?></td>
                        <td> <?=$id->duracion?></td>
                        <td> <?=$id->artista?></td>
                        <td> <?=$id->genero?></td>
                        <td> <?=$id->lanzamiento?></td>
                        
            
            

</tr>

</table>